apiVersion: v1
kind: Service
metadata:
  name: pingdirectory-headless
  namespace: ping-dev
spec:
  clusterIP: None
  selector:
    app: pingdirectory
  ports:
  - name: ldap
    port: 389
  - name: ldaps
    port: 636
---
apiVersion: v1
kind: Service
metadata:
  name: pingdirectory
  namespace: ping-dev
spec:
  selector:
    app: pingdirectory
  ports:
  - name: ldaps
    port: 636
    targetPort: 636
